### ISSUE TITLE
Application not working!

### ISSUE THREAD

**Issue by lovebdsobuj** [indywidualny/Centrum.fm#2]
Chk the video... [Centrum.fm app forced closed](https://www.dropbox.com/s/dg21upmgwpxyhh1/Centrum.fm%20app%20forced%20closed.mp4?dl=0)

**Comment by indywidualny** [comment]
Fixed in 37945b401692d72629b320331233ab40521ca980

**Comment by lovebdsobuj** [comment]
Well, it works now...

**Comment by indywidualny** [comment]
It's gonna be released soon. A few people is testing it right now. But it's actually a very specific app for a radio station, mainly for Polish users. No translations are planned etc. But I'm glad you use it :)

**Comment by lovebdsobuj** [comment]
Beautiful app design! 
Small app size, but very user friendly interface, Nice! 
It's for you :heart:
