### ISSUE TITLE
Can I get server-side code

### ISSUE THREAD

**Issue by lovebdsobuj** [indywidualny/Centrum.fm#3]
Can I get server-side code `/centrum/`

**Comment by lovebdsobuj** [comment]
Sorry, I found it here... [Serwer (pośrednik)](https://github.com/indywidualny/Centrum.fm/blob/master/server)

**Comment by indywidualny** [comment]
It's nothing fancy. Just a simple script to avoid heavy traffic on radio station server. I'm serving a copy of its content through my own web server :)

**Comment by lovebdsobuj** [comment]
But, how is generate automatically `teraz.txt` & `zaraz.txt`...?

**Comment by indywidualny** [comment]
It's obtained every minute from the radio website. I'm not generating it. I suppose they have a script which gets data from currently played audio files. I don't know the specifics but it seems simple. Just a small shell script which gets tags from mp3 / flac files. I suppose that's how it's made.

**Comment by lovebdsobuj** [comment]
Is these script enough [Serwer (pośrednik)](https://github.com/indywidualny/Centrum.fm/blob/master/server) for generating automatically `teraz.txt` & `zaraz.txt` file...?

Or different script for that...?

**Comment by indywidualny** [comment]
Something different. Those PHP scripts are only to convert two CSV files to a JSON array. The app uses it as its API endpoint.

**Comment by lovebdsobuj** [comment]
Why I give you smile, because for fast reply.

Okay, 

Can I get the script for generating `teraz.txt` & `zaraz.txt` file...?

**Comment by indywidualny** [comment]
Unfortunatelly I don't have it. I created this app but I'm not involved with the station. I'm just a fan.

**Comment by lovebdsobuj** [comment]
Oh! 
I think the script stored here http://indywidualni.org/centrum/

**Comment by indywidualny** [comment]
That's the "live" location of [Serwer (pośrednik)](https://github.com/indywidualny/Centrum.fm/blob/master/server). But as I said, it only serves JSON output of data generated by the radio station ;)

**Comment by lovebdsobuj** [comment]
This text file how to generate? http://indywidualni.org/centrum/zaraz.txt

**Comment by indywidualny** [comment]
No idea. It's auto downloaded.
