### ISSUE TITLE
What about you google-services.json?

### ISSUE THREAD

**Issue by lovebdsobuj** [indywidualny/Centrum.fm#6]
What about [google-services.json](https://github.com/indywidualny/Centrum.fm/blob/master/app/google-services.json)...?

**Comment by indywidualny** [comment]
What's with it? Nothing crucial isn't shared. It's just for Google analytics. Not authentication etc. So IMHO it can be inside the repository. Just project ID and Analytics ID.

**Comment by lovebdsobuj** [comment]
It's part of new Gradle Plugin for Google Services...? [The Google Services Gradle Plugin](https://developers.google.com/android/guides/google-services-plugin)

**Comment by indywidualny** [comment]
Yes. The new way of using Google Services. I could use something open source but I like Google Analytics. It's just convenient and simple. I needed to track app problems.

**Comment by lovebdsobuj** [comment]
Great, 
It was very nice implement...

**Comment by indywidualny** [comment]
Well. The file is auto generated in Google programmer's console. And the implementation is just standard :)

**Comment by lovebdsobuj** [comment]
Yeah, really... 
Here is the link for [Add Google Services  |  Google Developers](https://developers.google.com/mobile/add?platform=android) console.
